Rhel8 9 nullptr dereference
datto/dattobd pull request #377
Opened 2024-06-17 15:52 UTC by AlexScherba16

- changes in block_device in kernel
- support new linux kernel function declarations
- support for bd_has_submit_bio for block device

2024-06-17 15:57 UTC, st-matskevich approved these changes

2024-06-18 20:40 UTC, Swistusmen commented
Is it all copied from https://github.com/datto/dattobd/compare/main...Swistusmen:dattobd:supporting-ubuntu24 and https://github.com/datto/dattobd/pull/367 + changes made here: https://github.com/datto/dattobd/pull/377/commits/e9e8df1904301842cc6ab659068dba31ecc44fec?

2024-06-18 20:47 UTC, AlexScherba16 commented
@Swistusmen without changes in tracer.

2024-06-20 19:56 UTC, Swistusmen commented on src/blkdev.c
> +void dattobd_drop_super(struct super_block *sb)
Pls simplify to #if defined HAVE_GET_SUPER return drop_super(sb) #endif return;

2024-06-20 19:57 UTC, Swistusmen requested changes
Pls simplify dattobd_drop_super

2024-09-09 13:40 UTC, iamandrii commented
Included to #382

2024-09-09 13:40 UTC, closed without merging